formatter: markdown table

header-from: main.tf
footer-from: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true

sections:
  modules:
    - src/modules/alerting
    - src/modules/grafana
    - src/modules/logging
    - src/modules/otel-collector
    - src/modules/prometheus
    - src/modules/trace-backend
